const CondoList: string[] = [
  "Premium Place Ekamai - Rarm Intra 2",
  "The Loft by I-ZEN Nakniwat 48",
  "Baan Klang Muang Swiss Town Kaset-Nawamin",
  "Baan Klang Muang Urbanion Ladprao - Chokchai 4",
  "AREEYA MOVA KASET-NAWAMINTR",
  "Baan Klang Muang Ladprao-Yothin Phatthana",
  "Baan Klang Muang Urbanion Ladprao Sena 2",
  "I Place",
  "ECO SPACE KASET-NAWAMIN",
  "Baan Klang Muang Ladprao 71",
  "The Plant Citi Ladphrao 71",
  "The Tierra Ladprao 71",
  "Panasiri Residences Kaset-Nawamin",
  "Casa City The Spirit Ekamai – Ramindra 2",
  "Patra villa 8 Chokchai 4 - Ladprao 71",
  "The Landmark Ekamai-Ramindra",
  "Plus City Park Ladphrao 71",
  "Premium Place Kaset - Nawamin 2",
  "Pradya Hometown",
  "Baanpuripuri Satriwittaya 2",
  "Private Nirvana Ladprao Life Ladprao 71",
  "Casa City Sukontasawat 2",
  "Areeya The Color 2 Lat Pla Khao",
  "Golden Town Ladprao – Kaset nawamin",
  "D Space Chokchai 4",
  "Casa City Ekkamai - Ramintra",
  "AREEYA DAILY KASET-NAWAMINTR",
  "Cozy Satreewittaya 2 Soi 10",
  "Via Botani (Sukhumvit 47)",
  "H2 Condo รามอินทรา 21",
  "คอนโด วัน สุขุมวิท 52",
  "The Base Park East Sukhumvit 77",
  "Aspire Asoke-Ratchada",
  "Hasu Haus (Soi Onnut 1/1)",
  "The Line sukhumvit 101",
];

export default CondoList;
