export interface StationInfo {
  code: string
  th: string
  en?: string
  synonym?: string
}

export const stations: StationInfo[] = [
  //BTS Silom Line
  { code: "W1", th: "BTS สนามกีฬาแห่งชาติ", en: "BTS National Stadium" },
  { code: "S01", th: "BTS ราชดำริ", en: "BTS Ratchadamri" },
  { code: "S02", th: "BTS ศาลาแดง", en: "BTS Sala Daeng" },
  { code: "S03", th: "BTS ช่องนนทรี", en: "BTS Chong Nonsi" },
  { code: "S04", th: "BTS เซนต์หลุยส์", en: "BTS Saint Louis" },
  { code: "S05", th: "BTS สุรศักดิ์", en: "BTS Surasak" },
  { code: "S06", th: "BTS สะพานตากสิน", en: "BTS Saphan Taksin" },
  { code: "S07", th: "BTS กรุงธนบุรี", en: "BTS Krung Thon Buri", synonym: "BTS กรุงธน" },
  { code: "S08", th: "BTS วงเวียนใหญ่", en: "BTS Wongwian Yai" },
  { code: "S09", th: "BTS โพธิ์นิมิตร", en: "BTS Pho Nimit" },
  { code: "S10", th: "BTS ตลาดพลู", en: "BTS Talat Phlu" },
  { code: "S11", th: "BTS วุฒากาศ", en: "BTS Wutthakat" },
  { code: "S12", th: "BTS บางหว้า", en: "BTS Bang Wa" },

  //BTS Sukhumvit Line (Green Line)
  { code: "N24", th: "BTS คูคต", en: "BTS Khu Khot" },
  { code: "N23", th: "BTS แยก คปอ.", en: "BTS Yaek Kor Por Aor" },
  { code: "N22", th: "BTS พิพิธภัณฑ์กองทัพอากาศ ", en: "BTS Royal Thai Air Force Museum" },
  { code: "N21", th: "BTS โรงพยาบาลภูมิพลอดุลยเดช", en: "BTS Bhumibol Adulyadej Hospital" },
  { code: "N20", th: "BTS สะพานใหม่", en: "BTS Saphan Mai" },
  { code: "N19", th: "BTS สายหยุด", en: "BTS Sai Yud" },
  { code: "N18", th: "BTS พหลโยธิน 59", en: "BTS Phahon Yothin 59" },
  { code: "N17", th: "BTS วัดพระศรีมหาธาตุ", en: "BTS Wat Phra Sri Mahathat" },
  { code: "N16", th: "BTS กรมทหารราบที่ 11 ", en: "BTS 11th Infantry Regiment" },
  { code: "N15", th: "BTS บางบัว", en: "BTS Bang Bua" },
  { code: "N14", th: "BTS กรมป่าไม้", en: "BTS Royal Forest Department" },
  { code: "N13", th: "BTS มหาวิทยาลัยเกษตรศาสตร์", en: "BTS Kasetsart University" },
  { code: "N12", th: "BTS เสนานิคม", en: "BTS Sena Nikhom" },
  { code: "N11", th: "BTS รัชโยธิน", en: "BTS Ratchayothin" },
  { code: "N10", th: "BTS พหลโยธิน 24", en: "BTS Phahon Yothin 24" },
  { code: "N9", th: "BTS ห้าแยกลาดพร้าว", en: "BTS Ha Yaek Lat Phrao" },
  { code: "N8", th: "BTS หมอชิต", en: "BTS Mo Chit" },
  { code: "N7", th: "BTS สะพานควาย", en: "BTS Saphan Khwai" },
  { code: "N5", th: "BTS อารีย์", en: "BTS Ari" },
  { code: "N4", th: "BTS สนามเป้า", en: "BTS Sanam Pao" },
  { code: "N3", th: "BTS อนุสาวรีย์ชัยสมรภูมิ", en: "BTS Victory Monument" },
  { code: "N2", th: "BTS พญาไท", en: "BTS Phaya Thai" },
  { code: "N1", th: "BTS ราชเทวี", en: "BTS Ratchathewi" },
  { code: "CEN", th: "BTS สยาม", en: "BTS Siam" },

  //BTS Sulhumvit Line (Green Line)
  { code: "E01", th: "BTS ชิดลม", en: "BTS Chidlom" },
  { code: "E02", th: "BTS เพลินจิต", en: "BTS Phloen Chit" },
  { code: "E03", th: "BTS นานา", en: "BTS Nana" },
  { code: "E04", th: "BTS อโศก", en: "BTS Asok", synonym: "BTS Asoke" },
  { code: "E05", th: "BTS พร้อมพงษ์", en: "BTS Phrom Phong" },
  { code: "E06", th: "BTS ทองหล่อ", en: "BTS Thong Lo" },
  { code: "E07", th: "BTS เอกมัย", en: "BTS Ekkamai" },
  { code: "E08", th: "BTS พระโขนง", en: "BTS Phra Khanong" },
  { code: "E09", th: "BTS อ่อนนุช", en: "BTS On Nut" },
  { code: "E10", th: "BTS บางจาก", en: "BTS Bang Chak" },
  { code: "E11", th: "BTS ปุณณวิถี", en: "BTS Punnawithi" },
  { code: "E12", th: "BTS อุดมสุข", en: "BTS Udom Suk" },
  { code: "E13", th: "BTS บางนา", en: "BTS Bang Na" },
  { code: "E14", th: "BTS แบริ่ง", en: "BTS Bearing" },
  { code: "E15", th: "BTS สำโรง", en: "BTS Samrong" },
  { code: "E16", th: "BTS ปู่เจ้า", en: "BTS Pu Chao" },
  { code: "E17", th: "BTS ช้างเอราวัณ", en: "BTS Chang Erawan", synonym: "BTS Erawan" },
  { code: "E18", th: "BTS โรงเรียนนายเรือ", en: "BTS Royal Thai Naval Academy" },
  { code: "E19", th: "BTS ปากน้ำ", en: "BTS Pak Nam" },
  { code: "E20", th: "BTS ศรีนครินทร์", en: "BTS Srinagarindra" },
  { code: "E21", th: "BTS แพรกษา", en: "BTS Phraek Sa" },
  { code: "E22", th: "BTS สายลวด", en: "BTS Sai Luat" },
  { code: "E23", th: "BTS เคหะฯ ", en: "BTS Kheha" },

  //APM Gold Line (IconSiam)
  { code: "G2", th: "BTS เจริญนคร", en: "BTS Charoen Nakhon" },
  { code: "G3", th: "BTS คลองสาน", en: "BTS Khlong San" },

  //ARL Airport Rail Link
  { code: "A1", th: "ARL สุวรรณภูมิ", en: "ARL Suvarnabhumi" },
  { code: "A2", th: "ARL ลาดกระบัง", en: "ARL Lat Krabang" },
  { code: "A3", th: "ARL บ้านทับช้าง", en: "ARL Ban Thap Chang" },
  { code: "A4", th: "ARL หัวหมาก", en: "ARL Hua Mak" },
  { code: "A5", th: "ARL รามคำแหง", en: "ARL Ramkhamhaeng" },
  { code: "A6", th: "ARL มักกะสัน", en: "ARL Makkasan" },
  { code: "A7", th: "ARL ราชปรารภ", en: "ARL Ratchaprarop" },
  { code: "A8", th: "ARL พญาไท", en: "ARL Phaya Thai" },

  //MRT Blue line

  //MRT Blue line
  { code: "BL01", th: "MRT ท่าพระ", en: "MRT Tha Phra" },
  { code: "BL02", th: "MRT จรัญฯ 13", en: "MRT Charan 13" },
  { code: "BL03", th: "MRT ไฟฉาย", en: "MRT Fai Chai" },
  { code: "BL04", th: "MRT บางขุนนนท์", en: "MRT Bang Khun Non" },
  { code: "BL05", th: "MRT บางยี่ขัน", en: "MRT Bang Yi Khan" },
  { code: "BL06", th: "MRT สิรินธร", en: "MRT Sirindhorn" },
  { code: "BL07", th: "MRT บางพลัด", en: "MRT Bang Phlat" },
  { code: "BL08", th: "MRT บางอ้อ", en: "MRT Bang O" },
  { code: "BL09", th: "MRT บางโพ", en: "MRT Bang Pho" },
  { code: "BL10", th: "MRT เตาปูน", en: "MRT Tao Poon" }, //interchange
  { code: "BL11", th: "MRT บางซื่อ", en: "MRT Bang Sue" },
  { code: "BL12", th: "MRT กำแพงเพชร", en: "MRT Kamphaeng Phet" },
  { code: "BL13", th: "MRT จตุจักร", en: "MRT Mo Chit / Chatuchak Park" },
  { code: "BL14", th: "MRT พหลโยธิน", en: "MRT Phahon Yothin" },
  { code: "BL15", th: "MRT ลาดพร้าว", en: "MRT Lat Phrao" },
  { code: "BL16", th: "MRT รัชดาภิเษก", en: "MRT Ratchadaphisek" },
  { code: "BL17", th: "MRT สุทธิสาร", en: "MRT Sutthisan" },
  { code: "BL18", th: "MRT ห้วยขวาง", en: "MRT Huai Khwang" },
  { code: "BL19", th: "MRT ศูนย์วัฒนธรรมแห่งประเทศไทย", en: "MRT Thailand Cultural Centre" },
  { code: "BL20", th: "MRT พระราม 9", en: "MRT Phra Ram 9" },
  { code: "BL21", th: "MRT เพชรบุรี", en: "MRT Phetchaburi" },
  { code: "BL22", th: "MRT สุขุมวิท", en: "MRT Sukhumvit" },
  { code: "BL23", th: "MRT ศูนย์การประชุมแห่งชาติสิริกิติ์", en: "MRT Queen Sirikit National Convention Centre" },
  { code: "BL24", th: "MRT คลองเตย", en: "MRT Khlong Toei" },
  { code: "BL25", th: "MRT ลุมพินี", en: "MRT Lumphini" },
  { code: "BL26", th: "MRT สีลม", en: "MRT Si Lom" },
  { code: "BL27", th: "MRT สามย่าน", en: "MRT Sam Yan" },
  { code: "BL28", th: "MRT หัวลำโพง", en: "MRT Hua Lamphong" },
  { code: "BL29", th: "MRT วัดมังกร", en: "MRT Wat Mangkon" },
  { code: "BL30", th: "MRT สามยอด", en: "MRT Sam Yot" },
  { code: "BL31", th: "MRT สนามไชย", en: "MRT Sanam Chai" },
  { code: "BL32", th: "MRT อิสรภาพ", en: "MRT Itsaraphap" },
  { code: "BL33", th: "MRT บางไผ่", en: "MRT Bang Phai" },
  { code: "BL34", th: "MRT บางหว้า", en: "MRT Bang Wa" },
  { code: "BL35", th: "MRT เพชรเกษม 48", en: "MRT Phetkasem 48" },
  { code: "BL36", th: "MRT ภาษีเจริญ", en: "MRT Phasi Charoen" },
  { code: "BL37", th: "MRT บางแค", en: "MRT Bang Khae" },
  { code: "BL38", th: "MRT หลักสอง", en: "MRT Lak Song" },

  //MRT Purple line
  { code: "PP01", th: "MRT คลองบางไผ่", en: "MRT Khlong Bang Phai" },
  { code: "PP02", th: "MRT ตลาดบางใหญ่", en: "MRT Talad Bang Yai" },
  { code: "PP03", th: "MRT สามแยกบางใหญ่", en: "MRT Sam Yaek Bang Yai" },
  { code: "PP04", th: "MRT บางพลู", en: "MRT Bang Phlu" },
  { code: "PP05", th: "MRT บางรักใหญ่", en: "MRT Bang Rak Yai" },
  { code: "PP06", th: "MRT บางรักน้อยท่าอิฐ", en: "MRT Bang Rak Noi Tha It" },
  { code: "PP07", th: "MRT ไทรม้า", en: "MRT Sai Ma" },
  { code: "PP08", th: "MRT สะพานพระนั่งเกล้า", en: "MRT Phra Nangklao Bridge" },
  { code: "PP09", th: "MRT แยกนนทบุรี 1", en: "MRT Yaek Nonthaburi 1" },
  { code: "PP10", th: "MRT บางกระสอ", en: "MRT Bang Krasor" },
  { code: "PP11", th: "MRT ศูนย์ราชการนนทบุรี", en: "MRT Nonthaburi Civic Centre" },
  { code: "PP12", th: "MRT กระทรวงสาธารณสุข", en: "MRT Ministry Of Public Health" },
  { code: "PP13", th: "MRT แยกติวานนท์", en: "MRT Yaek Tiwanon" },
  { code: "PP14", th: "MRT วงศ์สว่าง", en: "MRT Wong Sawang" },
  { code: "PP15", th: "MRT บางซ่อน", en: "MRT Bang Son" },
  { code: "PP16", th: "MRT เตาปูน", en: "MRT Tao Poon (M)" }, //interchange

  //BTS Pink line
  { code: "PK01", th: "MRT ศูนย์ราชการนนทบุรี", en: "MRT Nonthaburi Government Center" },
  { code: "PK02", th: "MRT แคราย", en: "MRT Khae Rai" },
  { code: "PK03", th: "MRT สนามบินน้ำ", en: "MRT Sanambin Nam" },
  { code: "PK04", th: "MRT สามัคคี", en: "MRT Samakkhi" },
  { code: "PK05", th: "MRT กรมชลประทาน", en: "MRT Royal Irrigation Department" },
  { code: "PK06", th: "MRT แยกปากเกร็ด", en: "MRT Pak Kret" },
  { code: "PK07", th: "MRT เลี่ยงเมืองปากเกร็ด", en: "MRT Pak Kret Bypass" },
  { code: "PK08", th: "MRT แจ้งวัฒนะ-ปากเกร็ด 28", en: "MRT Chaeng Watthana-Pak Kret 28" },
  { code: "PK09", th: "MRT ศรีรัช", en: "MRT Si Rat" },
  { code: "PK10", th: "MRT เมืองทองธานี", en: "MRT Mueang Thong Thani" },
  { code: "PK11", th: "MRT แจ้งวัฒนะ 14", en: "MRT Chaeng Watthana 14" },
  { code: "PK12", th: "MRT ศูนย์ราชการเฉลิมพระเกียรติ", en: "MRT Bangkok Government Complex" },
  { code: "PK13", th: "MRT โทรคมนาคมแห่งชาติ", en: "MRT TOT" },
  { code: "PK14", th: "MRT หลักสี่", en: "MRT Lak Si" },
  { code: "PK15", th: "MRT ราชภัฎพระนคร", en: "MRT Phranakhon Rajabhat University" },
  { code: "PK16", th: "MRT วัดพระศรีมหาธาตุ", en: "MRT Wat Phra Si Maha" },
  { code: "PK17", th: "MRT รามอินทรา 3", en: "MRT Ram Inthra 3" },
  { code: "PK18", th: "MRT ลาดปลาเค้า", en: "MRT Lat Pla Khao" },
  { code: "PK19", th: "MRT รามอินทรา กม. 4", en: "MRT Ram Inthra 31 " },
  { code: "PK20", th: "MRT มัยลาภ", en: "MRT Maiyalap" },
  { code: "PK21", th: "MRT วัชรพล", en: "MRT Watcharaphon" },
  { code: "PK22", th: "MRT รามอินทรา กม. 6", en: "MRT Ram Inthra 40" },
  { code: "PK23", th: "MRT คู้บอน", en: "MRT Khu Bon" },
  { code: "PK24", th: "MRT รามอินทรา กม. 9", en: "MRT Ram Inthra 83" },
  { code: "PK25", th: "MRT วงแหวนรามอินทรา", en: "MRT East Outer Ring Road" },
  { code: "PK26", th: "MRT นพรัตน์", en: "MRT Nopparat Rajathanee" },
  { code: "PK27", th: "MRT บางชัน", en: "MRT Bang Chan" },
  { code: "PK28", th: "MRT เศรษฐบุตรบำเพ็ญ", en: "MRT Setthabutbamphen" },
  { code: "PK29", th: "MRT ตลาดมีนบุรี", en: "MRT Min Buri Market" },
  { code: "PK30", th: "MRT มีนบุรี", en: "MRT Min Buri" },
  { code: "MT01", th: "MRT อิมแพ็ค เมืองทองธานี", en: "MRT ____" },
  { code: "MT02", th: "MRT ทะเลสาบเมืองทองธานี", en: "MRT ____" },

  //SRT = State Railway of Thailand
  //SRT Light Red Line (Nakhon Withi Line)
  { code: "RE08", th: "SRT หัวหมาก", en: "SRT Hua Mak" },
  { code: "RE07", th: "SRT รามคำแหง", en: "SRT Ramkhamhaeng" },
  { code: "RE06", th: "SRT ศูนย์วิจัย", en: "SRT Sun Wichai" },
  { code: "RE05", th: "SRT มักกะสัน", en: "SRT Makkasan" },
  { code: "RE04", th: "SRT พญาไท", en: "SRT Phaya Thai" },
  { code: "RE03", th: "SRT ราชวิถี", en: "SRT Ratchawithi" },
  { code: "RE02", th: "SRT สามเสน", en: "SRT Sam Sen" },
  { code: "RE01", th: "SRT ประดิพัทธ์", en: "SRT Pradiphat" },
  { code: "RW01", th: "SRT บางซื่อ", en: "SRT Bang Sue" },
  { code: "RW02", th: "SRT บางซ่อน", en: "SRT Bang Son" },
  { code: "RW03", th: "SRT พระราม 6", en: "SRT Phra Ram 6" },
  { code: "RW04", th: "SRT บางกรวย-กฟผ. ", en: "SRT Bang Kruai-EGAT" },
  { code: "RW05", th: "SRT บางบำหรุ", en: "SRT Bang Bamru" },
  { code: "RW06", th: "SRT ตลิ่งชัน", en: "SRT Taling Chan" },
  { code: "RW07", th: "SRT บ้านฉิมพลี", en: "SRT Ban Chimphli" },
  { code: "RW08", th: "SRT กาญจนาภิเษก", en: "SRT Kanchanaphisek" },
  { code: "RW09", th: "SRT ศาลาธรรมสพน์", en: "SRT Sala Thammasop" },
  { code: "RW10", th: "SRT ศาลายา", en: "SRT Sala Ya" },

  //SRT Dark Red Line (Thani Ratthaya Line)
  { code: "RN10", th: "SRT รังสิต,", en: "SRT Rangsit" },
  { code: "RN09", th: "SRT หลักหก (มหาวิทยาลัยรังสิต)", en: "SRT Lak Hok (Rangsit University)" },
  { code: "RN08", th: "SRT ดอนเมือง,", en: "SRT Don Mueang" },
  { code: "RN07", th: "SRT การเคหะ", en: "SRT Kan Kheha" },
  { code: "RN06", th: "SRT หลักสี่", en: "SRT Lak Si" },
  { code: "RN05", th: "SRT ทุ่งสองห้อง", en: "SRT Thung Song Hong" },
  { code: "RN04", th: "SRT บางเขน", en: "SRT Bang Khen" },
  { code: "RN03", th: "SRT วัดเสมียนนารี", en: "SRT Wat Samian Nari" },
  { code: "RN02", th: "SRT จตุจักร", en: "SRT Chatuchak" },
  { code: "RN01", th: "SRT บางซื่อ,", en: "SRT Bang Sue" },

  //MRT Yellow Line
  { code: "YLEX-02", th: "BTS พหลโยธิน 24,", en: "BTS Phaholyothin 24" },
  { code: "YLEX-01", th: "BTS จันทรเกษม,", en: "BTS Chankasem" },
  { code: "YL01", th: "BTS ลาดพร้าว,", en: "BTS Lat Phrao" },
  { code: "YL02", th: "BTS ภาวนา,", en: "BTS Phawana" },
  { code: "YL03", th: "BTS โชคชัย 4,", en: "BTS Chok Chai 4" },
  { code: "YL04", th: "BTS ลาดพร้าว 71,", en: "BTS Lat Phrao 71" },
  { code: "YL05", th: "BTS ลาดพร้าว 83,", en: "BTS Lat Phrao 83" },
  { code: "YL06", th: "BTS มหาดไทย,", en: "BTS Mahatthai" },
  { code: "YL07", th: "BTS ลาดพร้าว 101,", en: "BTS Lat Phrao 101" },
  { code: "YL08", th: "BTS บางกะปิ,", en: "BTS Bang Kapi" },
  { code: "YL09", th: "BTS แยกลำสาลี,", en: "BTS Yaek Lam Sali" },
  { code: "YL10", th: "BTS ศรีกรีฑา,", en: "BTS Si Kritha" },
  { code: "YL11", th: "BTS หัวหมาก,", en: "BTS Hua Mak" },
  { code: "YL12", th: "BTS กลันตัน,", en: "BTS Khlong Kalantan" },
  { code: "YL13", th: "BTS ศรีนุช,", en: "BTS Si Nut" },
  { code: "YL14", th: "BTS ศรีนครินทร์ 38,", en: "BTS Srinagarindra 38" },
  { code: "YL15", th: "BTS สวนหลวง ร.9,", en: "BTS Suan Luang Rama IX" },
  { code: "YL16", th: "BTS ศรีอุดม,", en: "BTS Si Udom" },
  { code: "YL17", th: "BTS ศรีเอี่ยม,", en: "BTS Si Iam (Depot)" },
  { code: "YL18", th: "BTS ศรีลาซาล,", en: "BTS Si La Salle" },
  { code: "YL19", th: "BTS ศรีแบริ่ง,", en: "BTS Si Bearing" },
  { code: "YL20", th: "BTS ศรีด่าน,", en: "BTS Si Dan" },
  { code: "YL21", th: "BTS ศรีเทพา,", en: "BTS Si Thepha" },
  { code: "YL22", th: "BTS ทิพวัล,", en: "BTS Thipphawan" },
  { code: "YL23", th: "BTS สำโรง (สีเหลือง)", en: "BTS Samrong" },

  //Orange Line
  { code: "OR13", th: "MRT ศูนย์วัฒนธรรมแห่งประเทศไทย (สีส้ม)", en: "MRT Thailand Cultural Centre (Orange)" },
  { code: "OR14", th: "MRT รฟม", en: "MRT _____" },
  { code: "OR15", th: "MRT ประดิษฐ์มนูธรรม", en: "MRT _____" },
  { code: "OR16", th: "MRT รามคำแหง 12", en: "MRT _____" },
  { code: "OR17", th: "MRT รามคำแหง", en: "MRT _____" },
  { code: "OR18", th: "MRT ราชมังคลา", en: "MRT _____" },
  { code: "OR19", th: "MRT หัวหมาก", en: "MRT _____" },
  { code: "OR20", th: "MRT ลำสาลี", en: "MRT _____" },
  { code: "OR21", th: "MRT ศรีบูรพา", en: "MRT _____" },
  { code: "OR22", th: "MRT คลองบ้านม้า", en: "MRT _____" },
  { code: "OR23", th: "MRT สัมมากร", en: "MRT _____" },
  { code: "OR24", th: "MRT น้อมเกล้า", en: "MRT _____" },
  { code: "OR25", th: "MRT ราษฎร์พัฒนา", en: "MRT _____" },
  { code: "OR26", th: "MRT มีนพัฒนา", en: "MRT _____" },
  { code: "OR27", th: "MRT เคหะรามคำแหง", en: "MRT _____" },
  { code: "OR28", th: "MRT มีนบุรี (สีส้ม)", en: "MRT Min Buri" },
  { code: "OR29", th: "MRT สุวินทวงศ์", en: "MRT _____" },

  //Special places
  { code: "RM3", th: "พระราม 3" },
  { code: "CPN1", th: "เซ็นทรัลบางนา" },
]
